# .minion-blueprints/_template.sh — Blueprint contract documentation
# ================================================================
# This file documents the blueprint contract.
# NOT executed. Copy it to create a new blueprint.
#
# Usage:
#   1. Copy this file: cp _template.sh my-blueprint.sh
#   2. Define BLUEPRINT_TYPE and the required functions
#   3. Register in .minion.yml under `blueprints:`
#   4. Run: ./minion.sh my-blueprint "task"
#
# ================================================================
# CONTRACT
# ================================================================
#
# REQUIRED:
#   BLUEPRINT_TYPE="plan"|"direct"
#     - "plan": Uses 3 agents (planner + reviewer + executor)
#     - "direct": Uses 1 agent (direct executor)
#
#   execute_prompt()
#     - ALWAYS required
#     - Returns the prompt for the executor agent
#     - For type=plan: includes the approved plan via $RUN_PLAN_FILE
#     - For type=direct: includes the task directly
#
# REQUIRED if BLUEPRINT_TYPE="plan":
#   plan_prompt()
#     - Returns the prompt for the planner agent
#     - Should include the task ($TASK_CONTEXT) and rules ($CFG_EFFECTIVE_RULES)
#
# OPTIONAL (overrides):
#   fix_prompt()
#     - $1 = string with validation errors (ANSI stripped, tests summarized)
#     - If not defined, core generates a default prompt
#
#   review_criteria()
#     - Returns additional criteria for the reviewer
#     - Injected into the plan review prompt
#
# ================================================================
# AVAILABLE VARIABLES
# ================================================================
#
# From CLI:
#   $TASK            - The task as described by the user
#   $TASK_DISPLAY    - Display name (task ID + title, or free-form task)
#   $TASK_CONTEXT    - Full task context (from TAREAS.md or free-form)
#   $TASK_ID         - Task ID if provided (e.g., "F2-03"), empty otherwise
#   $BLUEPRINT       - Blueprint name (e.g., "implement")
#   $DRY_RUN         - "true" or "false"
#
# From config (.minion.yml):
#   $CFG_PROJECT_NAME       - Project name
#   $CFG_EFFECTIVE_RULES    - Global rules + blueprint rules
#   $CFG_BASE_BRANCH        - Base branch (e.g., "develop")
#   $CFG_CMD_*              - Commands (install, lint, format, etc.)
#
# From runtime (generated by core):
#   $RUN_ID          - Unique run identifier
#   $RUN_PLAN_FILE   - Path to approved plan (type=plan only, used in execute_prompt)
#   $RUN_REVIEW_FILE - Path to reviewer feedback (used internally by core)
#   $RUN_BRANCH      - Branch name created
#   $RUN_LOG         - Path to run log
#   $RUN_METRICS     - Path to metrics file
#   $RUN_TEMP_DIR    - Temp directory (cleaned up on exit)
